BROKER_URL = 'redis 주소'

CELERY_RESULT_BACKEND = "redis 주소"

CELERY_IMPORTS = ['tasks']
CELERY_TASK_RESULT_EXPIRES = 3600  # 1 hour
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_ACCEPT_CONTENT = ['json', 'yaml']
